if True: ## Contrôles 1J ##
    fl_g = 'left'
    fl_d = 'right'
    fl_h = 'up'
    fl_b = 2621440
    keys_hold = ['c']
    keys_soft_drop = [fl_b]
    keys_hard_drop = ['space']
    keys_rotate = [fl_h]
    keys_left = [fl_g]
    keys_h_left = []
    keys_right = [fl_d]
    keys_h_right = []
    keys_pause = ['p']
    keys_rot_CCW = ['z']
    keys_rot_CW = ['x']
    rotate_clocwise = True
if False: ## Contrôles 2J ##
    ## J1 ##
    fl_g = 2424832
    fl_d = 2555904
    fl_h = 2490368
    fl_b = 2621440
    keys_hold = ['c']
    keys_soft_drop = [fl_b]
    keys_rotate = [fl_h]
    keys_left = [fl_g]
    keys_h_left = []
    keys_right = [fl_d]
    keys_h_right = []
    keys_pause = ['p']
    keys_rot_CCW = ['z']
    keys_rot_CW = ['x']
    rotate_clocwise = True
    ## J2 ##
    keys_hold = ['c']
    keys_soft_drop = [fl_b]
    keys_rotate = [fl_h]
    keys_left = [fl_g]
    keys_h_left = []
    keys_right = [fl_d]
    keys_h_right = []
    keys_pause = ['p']
    keys_rot_CCW = ['z']
    keys_rot_CW = ['x']
    rotate_clocwise = True